### ISSUE TITLE
Crash loading

### ISSUE THREAD

**Issue by cpm9** [LinsMinecraftStudio/TitleChanger#2]
**Describe the bug**
Crash loading

**Desktop (please complete the following information):**
 - Java: 17.0.3
- Minecraft: 1.20.1
- Mod loader: Fabric loader 1.20.1 v0.14.21
- fabric-api-0.85.0+1.20.1
- TitleChanger-1.9-dev
- LinsAPI-1.4.5

[latest.log](https://github.com/LinsMinecraftStudio/TitleChanger/files/11970666/latest.log)

[crash-2023-07-06_11.20.13-client.txt](https://github.com/LinsMinecraftStudio/TitleChanger/files/11970665/crash-2023-07-06_11.20.13-client.txt)

**Comment by lijinhong11** [comment]
I will fix that

**Comment by lijinhong11** [comment]
Fixed in [1.9p1](https://modrinth.com/mod/mctitlechanger/version/1.9p1)
