### ISSUE TITLE
Constantly update title when switching user using In-Game Account Switcher

### ISSUE THREAD

**Issue by ray1997** [LinsMinecraftStudio/TitleChanger#4]
**Describe the bug**
When having %user% on a title somewhere, a mod will constantly update title after a user has been switched on In-Game Account Switcher

**To Reproduce**
1. Having "In-Game Account Switcher" mod
2. Config the Title to include %user%
3. Launch the game and switch account using In-Game Account Switcher mod
4. A title will constantly update between original username and switched username

**Expected behavior**
A title stay to either Original username or Switched username

**Desktop:**
 - Java: 17
- Minecraft: 1.20.1
- Mod loader: Fabric
- OS: Linux Mint 21

**Additional context**

**Comment by lijinhong11** [comment]
Can you display your title? I cannot accurately know your current situation.

**Comment by lijinhong11** [comment]
Fixed in version [1.9.2](https://modrinth.com/mod/mctitlechanger/version/1.9.2)
