### ISSUE TITLE
The mod cuase the crash

### ISSUE THREAD

**Issue by Juitar** [LinsMinecraftStudio/TitleChanger#7]
### Error

https://paste.gg/p/anonymous/ddc7705f61af4e47b3b18966b6b98489

### Modloader

minecraft 1.20.1 forge 47.3.5 HMCL

### Actions to reproduce

[minecraft-exported-crash-info-2024-08-18T11-30-13.zip](https://github.com/user-attachments/files/16647110/minecraft-exported-crash-info-2024-08-18T11-30-13.zip)

### TitleChanger version

mod version 1.10.1

### Other

opps

**Comment by lijinhong11** [comment]
这不是我的问题吧戈门

**Comment by Juitar** [comment]
啊嘞 可是我屏蔽掉这个模组就可以正常启动了

**Comment by lijinhong11** [comment]
你吧itlt和titlechanger装一起肯定冲突啊

**Comment by Juitar** [comment]
哦哦 可是我已经删除了哪个mod了 难道是配置文件还留着吗

**Comment by lijinhong11** [comment]
也许吧

**Comment by Juitar** [comment]
好的  乌龙了 抱歉了

**Comment by Juitar** [comment]
哎？ 我重新建立了一个1.20.1的版本 将mod复制过去（没有itlt） 仍然崩溃  我换了 PCL2 的启动器 日志如下 
[latest.log](https://github.com/user-attachments/files/16647186/latest.log)

**Comment by Juitar** [comment]
仅屏蔽该模组可以正常启动

**Comment by lijinhong11** [comment]
别的我也不清楚 单靠这些log完全不能体现tc有什么问题

**Comment by Juitar** [comment]
好吧

**Comment by Juitar** [comment]
换成tc 1.10版本的就正常启动了...

**Comment by lijinhong11** [comment]
整个项目我都决定弃坑了（

**Comment by Juitar** [comment]
弃坑吧 但是你的模组确实是标题切换比较特殊的 现在还能看pr 挺负责的
